# Generated by Django 5.0.3 on 2024-03-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noteapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="done_at",
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
